osx_image: xcode7.3
language: objective-c
xcode_project: Spectacle.xcodeproj
xcode_scheme: Spectacle

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform Mac

script:
  - set -o pipefail && xcodebuild -project Spectacle.xcodeproj -scheme Spectacle test | xcpretty
